import 'package:futudem_app/data/datasource/tournament_datasource.dart';
import 'package:futudem_app/models/repositories/tournament_repository.dart';
import 'package:futudem_app/models/team.dart';
import 'package:futudem_app/models/tournament.dart';

class TournamentRepositoryImpl implements TournamentRepository {
  final TournamentRemoteDatasource _datasource;

  TournamentRepositoryImpl(this._datasource);

  @override
  Future<void> createTournament(Tournament tournament) async {
    final newTournament = Tournament(
      id: 0, // Assuming the ID is auto-generated by the database
      name: tournament.name,
      startDate: tournament.startDate,
      isActive: tournament.isActive,
    );
    await _datasource.createTournament(newTournament);
  }

  @override
  Future<void> updateTournament(int id, String name) async {
    final tournament = Tournament(
      id: id,
      name: name,
      startDate: '2023-10-01', // Example date, replace with actual logic
      isActive: true, // Example status, replace with actual logic
    );
    await _datasource.updateTournament(tournament);
  }


  @override
  Future<List<Tournament>> getTournaments() async {
    return await _datasource.getTournaments();
  }

 
  @override
  Future<List<Team>> getTeamByTournament(int tournamentId) async {
    return await _datasource.fetchTeamsByTournament(tournamentId);
  }

  @override
  Future<Tournament> getTournamentById(int id) async {
    return await _datasource.getTournamentById(id);
  }

  @override
  Future<void> startTournament(int tournamentId) async {
    print('luiginieves with ID: $tournamentId');
    await _datasource.startTournament(tournamentId);
  }

}