// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPF-Yag2Ve37im1hPVpjJpVKeazNiz4lc',
    appId: '1:1068811887207:web:d64324a326399e1f392ac2',
    messagingSenderId: '1068811887207',
    projectId: 'futudem',
    authDomain: 'futudem.firebaseapp.com',
    storageBucket: 'futudem.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWTXfZqrpRUrYsNDWEc3M1e8MzpxpVDcA',
    appId: '1:1068811887207:android:30bb611eaf102e24392ac2',
    messagingSenderId: '1068811887207',
    projectId: 'futudem',
    storageBucket: 'futudem.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOwRfd68fe_vICvSLeIdjcCy4mkz35R7A',
    appId: '1:1068811887207:ios:b548037e229f8151392ac2',
    messagingSenderId: '1068811887207',
    projectId: 'futudem',
    storageBucket: 'futudem.firebasestorage.app',
    iosBundleId: 'com.example.futudemApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOwRfd68fe_vICvSLeIdjcCy4mkz35R7A',
    appId: '1:1068811887207:ios:b548037e229f8151392ac2',
    messagingSenderId: '1068811887207',
    projectId: 'futudem',
    storageBucket: 'futudem.firebasestorage.app',
    iosBundleId: 'com.example.futudemApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPF-Yag2Ve37im1hPVpjJpVKeazNiz4lc',
    appId: '1:1068811887207:web:8228f488fd88c3bd392ac2',
    messagingSenderId: '1068811887207',
    projectId: 'futudem',
    authDomain: 'futudem.firebaseapp.com',
    storageBucket: 'futudem.firebasestorage.app',
  );

}